dialogue_name = "fruitseller"

[[resources]]
name = "Fruits"
prompt = "Hvaða ávexti má bjóða þér?"
type = "ListResource"
repeatable = true
confirm_prompt =  "Viltu staðfesta ávextina {list_items}?"
repeat_prompt = "Pöntunin samanstendur af {list_items}. Verður það eitthvað fleira?"

[[resources]]
name = "Date"
type = "DatetimeResource"
prompt = "Hvenær viltu fá ávextina?"
time_fulfilled_prompt = "Afhendingin verður klukkan {time}. Hvaða dagsetningu viltu fá ávextina?"
date_fulfilled_prompt = "Afhendingin verður {date}. Klukkan hvað viltu fá ávextina?"
confirm_prompt = "Afhending pöntunar er {date_time}. Viltu staðfesta afhendinguna?"

# [[resources]]
# name = "Final"
# type = "FinalResource"
# prompt = "Pöntunin þín er {fruits} og verður afhent {date_time}."
# requires = ["Fruits", "Date"]
