dialogue_name = "fruitseller"

[[resources]]
name = "Fruits"
type = "ListResource"
# TODO: Keep singular and plural forms of fruits (or options more generally) for formatting answer
prompts.initial = "Hvaða ávexti má bjóða þér?"
prompts.options = "Ávextirnir sem eru í boði eru appelsínur, bananar, epli og perur."
prompts.empty = "Karfan er núna tóm. Hvaða ávexti má bjóða þér?"
prompts.confirm = "Viltu staðfesta ávextina {list_items}?"
prompts.repeat = "Pöntunin samanstendur af {list_items}. Verður það eitthvað fleira?"

[[resources]]
name = "Date"
type = "DatetimeResource"
prompts.initial = "Hvenær viltu fá ávextina?"
prompts.time_fulfilled = "Afhendingin verður klukkan {time}. Hvaða dagsetningu viltu fá ávextina?"
prompts.date_fulfilled = "Afhendingin verður {date}. Klukkan hvað viltu fá ávextina?"
prompts.confirm = "Afhending pöntunar er {date_time}. Viltu staðfesta afhendinguna?"

# [[resources]]
# name = "ConfirmOrder"
# type = "YesNoResource"
# prompt = "Viltu staðfesta þessa pöntun?"
# requires = ["Fruits", "Date"]

[[resources]]
name = "Final"
type = "FinalResource"
requires = ["Fruits", "Date"]
prompts.final = "Pöntunin þín er {fruits} og verður afhent {date_time}."
prompts.cancelled = "Móttekið, hætti við pöntunina."
